#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc config border_width         2
bspc config border_radius	 0 #10
bspc config window_gap           0 #6
bspc config top_padding		30

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

setxkbmap de &
~/.config/polybar/launch.sh &
python ~/.config/scripts/random_wallpaper.py &

# Notebook
xinput set-prop 14 319 1 &
sudo light -S 50 & # needs marlon ALL=NOPASSWD: /usr/bin/light after %wheel
xrandr --output HDMI1 --off
